### ISSUE TITLE
Why the name...

### ISSUE THREAD

**Issue by consp1racy** [WassimBenltaief/FlowLayout#1]
Here's what everybody thinks when FlowLayout is mentioned:
https://docs.oracle.com/javase/tutorial/uiswing/layout/flow.html
https://github.com/ApmeM/android-flowlayout
https://github.com/blazsolar/FlowLayout

**Comment by WassimBeltaief** [comment]
I refered to an android content view flow

> Why this layout ?
> - A very common flow of an android view is : 
> - show a progress bar while fetching data from a remote service.
> - if the resut is empty : show an empty view with a custom message and hide the progressbar.
> - If not : show the content and hide the progressbar.
> - showing a notification when phone is not connected or when action requires internet connection.

any other better name is welcome :)

**Comment by consp1racy** [comment]
You picked a name of an over a decade old standard Swing widget. That's not going to help anyone finding your library. It's also going to hinder anyone looking for a widget with the original functionality. Your choice of name was unfortunate.

Your widget does not "flow" or "represent flow". It represents _state_ of a data set presented to user. In any case please pick another name and verify it's unique or it does not clash with industry standards and it adequately represents the job at hand. Thank you.
