### ISSUE TITLE
Suggestion: Use Android SupportAnnotation like "@StringRes"

### ISSUE THREAD

**Issue by Rainer-Lang** [WassimBenltaief/FlowLayout#10]
see here: https://sites.google.com/a/android.com/tools/tech-docs/support-annotations

**Comment by WassimBeltaief** [comment]
+1 for this suggestion. I will work on that !

**Comment by WassimBeltaief** [comment]
I added @IntDef for the View modes (Progress, content, error, empty). The correct reference is here : d7e93091c376e60957167aae640ffe9652617c5f

**Comment by Rainer-Lang** [comment]
I thought even when setting texts like emptytext.

**Comment by WassimBeltaief** [comment]
yes you're right, some methods to set custom text, color, layout programmatically needs am annotation. I will add it.

**Comment by Rainer-Lang** [comment]
Thanks.
