### ISSUE TITLE
EmptyView: Possible to provide even an error image?

### ISSUE THREAD

**Issue by Rainer-Lang** [WassimBenltaief/FlowLayout#9]
It would be great to have the option to set an error image.

**Comment by WassimBeltaief** [comment]
Do you mean an error view with customizable layout ?

**Comment by WassimBeltaief** [comment]
I just added an error custom view. The referenced issue above is not the correct one. Check 4c7da621f36f1233e26dd05493a2aeee7d19c8d5

**Comment by Rainer-Lang** [comment]
Like here https://github.com/xiprox/ErrorView

**Comment by WassimBeltaief** [comment]
That's a good example. But my idea was to let it open to the developer to decide how to customize the error view with his own content. I think like that is better because it keeps the different layouts minimalists.

**Comment by Rainer-Lang** [comment]
I understand and agree.
